#!/usr/bin/env python3
"""
Script to resave DOCX files using LibreOffice to fix compatibility issues.

This script uses LibreOffice in headless mode to open and resave DOCX files
generated by Quarto. This normalizes the DOCX structure and fixes the
"Word found unreadable content" warning that appears when opening these files
in Microsoft Word.

The warning appears because Quarto/Pandoc-generated DOCX files may have
structural issues that Word doesn't like, especially when other tools
(like python-docx) try to modify them. LibreOffice can read and write
DOCX files in a way that fixes these compatibility issues.
"""

import os
import sys
import subprocess
import shutil
import tempfile
import traceback
from pathlib import Path


def check_libreoffice_installed():
    """Check if LibreOffice is installed and available."""
    try:
        result = subprocess.run(
            ['libreoffice', '--version'],
            capture_output=True,
            text=True,
            check=False
        )
        if result.returncode == 0:
            print(f"✓ LibreOffice found: {result.stdout.strip()}")
            return True
        else:
            print("✗ LibreOffice not found", file=sys.stderr)
            return False
    except FileNotFoundError:
        print("✗ LibreOffice not found in PATH", file=sys.stderr)
        return False


def resave_docx_with_libreoffice(docx_path, output_dir=None):
    """
    Resave a DOCX file using LibreOffice to fix compatibility issues.
    
    Args:
        docx_path: Path to the DOCX file to resave
        output_dir: Directory to save the resaved file (defaults to same directory)
    
    Returns:
        True if successful, False otherwise
    """
    docx_path = Path(docx_path)
    
    if not docx_path.exists():
        print(f"  ✗ File not found: {docx_path}", file=sys.stderr)
        return False
    
    # Use the same directory if no output directory specified
    if output_dir is None:
        output_dir = docx_path.parent
    else:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
    
    # Create a temporary directory for LibreOffice to write to
    temp_dir = Path(tempfile.mkdtemp(prefix='libreoffice-resave-'))
    
    try:
        # Use LibreOffice to convert (resave) the DOCX file
        # The --convert-to option forces LibreOffice to read and write the file,
        # which normalizes the structure
        result = subprocess.run(
            [
                'libreoffice',
                '--headless',
                '--convert-to', 'docx:"MS Word 2007 XML"',
                '--outdir', str(temp_dir),
                str(docx_path.absolute())
            ],
            capture_output=True,
            text=True,
            check=False,
            timeout=60
        )
        
        if result.returncode != 0:
            print(f"  ✗ LibreOffice conversion failed:", file=sys.stderr)
            print(f"    stdout: {result.stdout}", file=sys.stderr)
            print(f"    stderr: {result.stderr}", file=sys.stderr)
            return False
        
        # Find the converted file in the temp directory
        converted_file = temp_dir / docx_path.name
        
        if not converted_file.exists():
            print(f"  ✗ Converted file not found: {converted_file}", file=sys.stderr)
            return False
        
        # Move the converted file to replace the original
        final_path = output_dir / docx_path.name
        shutil.move(str(converted_file), str(final_path))
        
        print(f"  ✓ Successfully resaved: {docx_path.name}")
        return True
        
    except subprocess.TimeoutExpired:
        print(f"  ✗ LibreOffice conversion timed out for {docx_path.name}", file=sys.stderr)
        return False
    except Exception as e:
        print(f"  ✗ Error resaving {docx_path.name}: {e}", file=sys.stderr)
        traceback.print_exc()
        return False
    finally:
        # Clean up temp directory
        if temp_dir.exists():
            try:
                shutil.rmtree(temp_dir)
            except Exception as e:
                print(f"  ⚠ Warning: Failed to clean up temp directory {temp_dir}: {e}", file=sys.stderr)


def main():
    """Main function to process all DOCX files in the output directory."""
    # Get the DOCX directory from environment or use default
    docx_dir = os.getenv('DOCX_DIR', './docs')
    
    print("=" * 60)
    print("DOCX LibreOffice Resave")
    print("=" * 60)
    
    # Check if LibreOffice is installed
    print("\n1. Checking for LibreOffice...")
    if not check_libreoffice_installed():
        print("\n✗ LibreOffice is required but not found")
        print("  Please install LibreOffice to use this script")
        print("  On Ubuntu/Debian: sudo apt-get install libreoffice")
        sys.exit(1)
    
    # Find all DOCX files
    print(f"\n2. Finding DOCX files in {docx_dir}...")
    docx_files = list(Path(docx_dir).glob("*.docx"))
    
    if not docx_files:
        print("  ⚠ No DOCX files found")
        return
    
    print(f"  Found {len(docx_files)} DOCX file(s):")
    for docx_file in docx_files:
        print(f"    - {docx_file.name}")
    
    # Process each DOCX file
    print("\n3. Resaving DOCX files with LibreOffice...")
    success_count = 0
    for docx_file in docx_files:
        if resave_docx_with_libreoffice(docx_file):
            success_count += 1
    
    # Summary
    print("\n" + "=" * 60)
    print(f"DOCX resave complete: {success_count}/{len(docx_files)} successful")
    print("=" * 60)
    
    if success_count < len(docx_files):
        sys.exit(1)


if __name__ == '__main__':
    main()
