# Code repositories

Adapted by UCD-SeRG team from [original by Kunal Mishra, Jade Benjamin-Chung, and Stephanie Djajadi](https://jadebc.github.io/lab-manual/code-repositories.html)

Each study has at least one code repository that typically holds R code, shell scripts with Unix code, and research outputs (results .RDS files, tables, figures). Repositories may also include datasets. This chapter outlines how to organize these files. Adhering to a standard format makes it easier for us to efficiently collaborate across projects. 

UCD-SeRG projects use R package structure for all R-based work. This provides benefits for reproducibility, collaboration, and code quality even for analysis-only projects.

## Project Structure

{{< include 04-code-repositories/package-structure.qmd >}}

## `.Rproj` files

{{< include 04-code-repositories/rproj-files.qmd >}}


## Organizing the `data-raw` folder

{{< include 04-code-repositories/project-structure.qmd ?}}

## Configuration ('config') File

{{< include 04-code-repositories/config-file.qmd >}}

## Order Files and Directories

{{< include 04-code-repositories/order-files-directories.qmd >}}

## Using Bash scripts to ensure reproducibility

{{< include 04-code-repositories/bash-scripts.qmd >}}
