# R Coding Practices {#sec-r-coding-practices}

This chapter has moved to
[*Principles of Scientific Computing*](https://morrison-lab.github.io/psc/),
the Morrison Lab's general-purpose guide to coding for research projects:
**[R Coding Practices](https://morrison-lab.github.io/psc/chapters/coding-practices.html)**
(source: <https://github.com/Morrison-Lab/psc>).

[]{#sec-R6}
[]{#sec-adr-code-pointers}
[]{#sec-adr-format}
[]{#sec-adr-storage}
[]{#sec-adr-vs-pr}
[]{#sec-adr-when}
[]{#sec-adrs}
[]{#sec-auto-styling}
[]{#sec-benchmarking}
[]{#sec-callr}
[]{#sec-cli}
[]{#sec-constructive-feedback}
[]{#sec-covr}
[]{#sec-cpp11}
[]{#sec-crayon}
[]{#sec-data-io}
[]{#sec-decompose-qmd-chunks}
[]{#sec-decompose-validation}
[]{#sec-desc}
[]{#sec-devtools}
[]{#sec-documenting-code}
[]{#sec-dont-repurpose-tests}
[]{#sec-downlit}
[]{#sec-dplyr}
[]{#sec-forcats}
[]{#sec-fs}
[]{#sec-function-decomposition}
[]{#sec-function-length-limits}
[]{#sec-gargle}
[]{#sec-getting-help-with-code}
[]{#sec-ggplot2}
[]{#sec-gh}
[]{#sec-git-branches-and-tags}
[]{#sec-here-package-practices}
[]{#sec-here-pkg}
[]{#sec-httr}
[]{#sec-httr2}
[]{#sec-iteration}
[]{#sec-kiss}
[]{#sec-lifecycle}
[]{#sec-lintr}
[]{#sec-lobstr}
[]{#sec-lubridate}
[]{#sec-memoise}
[]{#sec-one-function-per-file}
[]{#sec-pak}
[]{#sec-pkgbuild}
[]{#sec-pkgcache}
[]{#sec-pkgdown}
[]{#sec-pkgload}
[]{#sec-prettyunits}
[]{#sec-processx}
[]{#sec-ps}
[]{#sec-purrr}
[]{#sec-r-lib-actions}
[]{#sec-r-lib-packages}
[]{#sec-r-package-tools}
[]{#sec-r-qa-checklist}
[]{#sec-r-resources}
[]{#sec-r-testing}
[]{#sec-r-version-control}
[]{#sec-r-workflow}
[]{#sec-rcmdcheck}
[]{#sec-readr}
[]{#sec-remotes}
[]{#sec-revdepcheck}
[]{#sec-reviewing-code}
[]{#sec-rex}
[]{#sec-rlang}
[]{#sec-roxygen2}
[]{#sec-scales}
[]{#sec-sessioninfo}
[]{#sec-snapshot-vs-explicit}
[]{#sec-stringr}
[]{#sec-styler}
[]{#sec-tdd}
[]{#sec-testing-best-practices}
[]{#sec-testthat}
[]{#sec-tibble}
[]{#sec-tidyr}
[]{#sec-tidyverse}
[]{#sec-tool-building}
[]{#sec-usethis}
[]{#sec-variable-labels}
[]{#sec-vctrs}
[]{#sec-waldo}
[]{#sec-what-to-look-for}
[]{#sec-when-to-approve}
[]{#sec-why-review-code}
[]{#sec-withr}

That page covers:

- [Lab Protocols for Code and Data](https://morrison-lab.github.io/psc/chapters/coding-practices.html#lab-protocols-for-code-and-data)
- [The Tool-Building Mindset](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-tool-building)
- [Essential R Package Development Tools](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-r-package-tools)
- [Complete Package Development Workflow](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-r-workflow)
- [Organizing scripts](https://morrison-lab.github.io/psc/chapters/coding-practices.html#organizing-scripts)
- [Testing Requirements](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-r-testing)
- [Test-Driven Development](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-tdd)
- [Benchmarking](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-benchmarking)
- [Iterative Operations](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-iteration)
- [Reading and Saving Data](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-data-io)
- [Version Control and Collaboration](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-r-version-control)
- [Quality Assurance Checklist](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-r-qa-checklist)
- [Automated Code Styling](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-auto-styling)
- [Documenting your code](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-documenting-code)
- [Design Documentation with ADRs](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-adrs)
- [Object naming](https://morrison-lab.github.io/psc/chapters/coding-practices.html#object-naming)
- [Function calls](https://morrison-lab.github.io/psc/chapters/coding-practices.html#function-calls)
- [Function decomposition](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-function-decomposition)
- [One function per file](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-one-function-per-file)
- [Function length limits](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-function-length-limits)
- [Keep It Short and Simple (KISS)](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-kiss)
- [Decomposing Code Chunks in Quarto Documents](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-decompose-qmd-chunks)
- [The here package](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-here-package-practices)
- [Reading/Saving Data](https://morrison-lab.github.io/psc/chapters/coding-practices.html#readingsaving-data)
- [Integrating Box and Dropbox](https://morrison-lab.github.io/psc/chapters/coding-practices.html#integrating-box-and-dropbox)
- [r-lib Packages](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-r-lib-packages)
- [Tidyverse](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-tidyverse)
- [Coding with R and Python](https://morrison-lab.github.io/psc/chapters/coding-practices.html#coding-with-r-and-python)
- [Repeating analyses with different variations](https://morrison-lab.github.io/psc/chapters/coding-practices.html#repeating-analyses-with-different-variations)
- [Reviewing Code](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-reviewing-code)
- [Getting Help with Code](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-getting-help-with-code)
- [Additional Resources](https://morrison-lab.github.io/psc/chapters/coding-practices.html#sec-r-resources)

::: {.callout-note collapse="true"}
## Looking for a specific section that used to be here?

This chapter's old `#sec-` anchors still resolve on this page,
so old bookmarks and links land here,
but the content now lives on the page linked above,
under the same anchor.
For example, `#sec-foo` here is `chapters/coding-practices.html#sec-foo` on the psc site.
:::
