name: Check Non-Standard Characters

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-chars:
    uses: d-morrison/gha/.github/workflows/check-non-standard-chars.yml@v2
